namespace WebApplication4.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class FirstName : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.FarmWorkers", "FarmWorkerImg", c => c.String());
            AddColumn("dbo.FarmWorkerTypes", "FarmWorkerTypeNotes", c => c.String(maxLength: 50));
            AddColumn("dbo.VehicleServices", "VehicleServiceRecordUnit", c => c.String(nullable: false, maxLength: 5));
            AlterColumn("dbo.Users", "UserName", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Users", "UserEmailAddress", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Users", "UserPassword", c => c.String(nullable: false, maxLength: 30));
            AlterColumn("dbo.Users", "UserFName", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Users", "UserLName", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.FarmWorkers", "FarmWorkerFName", c => c.String(nullable: false, maxLength: 15));
            AlterColumn("dbo.FarmWorkers", "FarmWorkerLName", c => c.String(nullable: false, maxLength: 15));
            AlterColumn("dbo.FarmWorkers", "Address", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.FarmWorkers", "Surburb", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.FarmWorkers", "City", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.FarmWorkers", "Country", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.FarmWorkers", "Province", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("dbo.FarmWorkerTypes", "FarmWorkerTypeDescr", c => c.String(nullable: false, maxLength: 30));
            AlterColumn("dbo.FarmWorkerTypes", "FarmWorkerTypeActiveStatus", c => c.String(nullable: false, maxLength: 10));
            AlterColumn("dbo.Genders", "GenderDescr", c => c.String(nullable: false, maxLength: 8));
            AlterColumn("dbo.Titles", "TitleDescr", c => c.String(nullable: false, maxLength: 8));
            AlterColumn("dbo.Audits", "AuditRefTable", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Audits", "TrxNewRecord", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Audits", "TrxOldRecord", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Audits", "AuditRefAtrribute", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Orders", "OrderItem", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Farms", "FarmName", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Lands", "LandName", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Fields", "FieldName", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.BiologicalDisasters", "BioDisasterDescr", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.BiologicalDisasters", "BioDisasterNotes", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.NaturalDisasters", "NatDisasterDescr", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.NaturalDisasters", "NatDisasterPrecautions", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.FieldStatus", "FieldStatDescr", c => c.String(nullable: false, maxLength: 25));
            AlterColumn("dbo.FieldStatus", "StatPreConditions", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.InventoryTreatments", "TreatmentUnit", c => c.String(nullable: false, maxLength: 5));
            AlterColumn("dbo.Inventories", "InvDescr", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Inventories", "InvCode", c => c.String(nullable: false, maxLength: 10));
            AlterColumn("dbo.Inventories", "InvSIUnit", c => c.String(nullable: false, maxLength: 5));
            AlterColumn("dbo.InventoryTypes", "InvTypeDescr", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Plantations", "RefugeSeedUnit", c => c.String(nullable: false, maxLength: 5));
            AlterColumn("dbo.Plantations", "ExpectedYieldUnit", c => c.String(nullable: false, maxLength: 5));
            AlterColumn("dbo.Plantations", "PlantationStatus", c => c.String(maxLength: 20));
            AlterColumn("dbo.CropCycles", "CropCycleDescr", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.CropTypes", "CropTypeDescr", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.CropTypes", "MaturityDays", c => c.Int(nullable: false));
            AlterColumn("dbo.FieldStages", "FieldStageDescr", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.Silos", "SiloDescr", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.Silos", "SiloStatus", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.Customers", "ContactPersonalEmailAddress", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Customers", "CompanyName", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Customers", "Address", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Customers", "Surburb", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Customers", "City", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Customers", "Country", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Customers", "Province", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.RainfallRecords", "RecordMeasurement", c => c.Int(nullable: false));
            AlterColumn("dbo.Provinces", "ProvinceDescr", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("dbo.Countries", "CountryDescr", c => c.String(nullable: false, maxLength: 25));
            AlterColumn("dbo.Vehicles", "VehModel", c => c.String(nullable: false, maxLength: 30));
            AlterColumn("dbo.Vehicles", "VehEngineNum", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Vehicles", "VehVinNum", c => c.String(nullable: false, maxLength: 17));
            AlterColumn("dbo.Vehicles", "VehRegNum", c => c.String(nullable: false, maxLength: 12));
            AlterColumn("dbo.Vehicles", "VehLicenseNum", c => c.String(nullable: false, maxLength: 15));
            AlterColumn("dbo.Vehicles", "VehServiceInterval", c => c.Int(nullable: false));
            AlterColumn("dbo.Vehicles", "VehServiceIntervalUnit", c => c.String(nullable: false, maxLength: 5));
            AlterColumn("dbo.VehicleMakes", "VehMakeDescr", c => c.String(nullable: false, maxLength: 30));
            AlterColumn("dbo.VehicleTypes", "VehTypeDescr", c => c.String(nullable: false, maxLength: 30));
            AlterColumn("dbo.VehicleTypes", "VehTypeImg", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.OrderStatus", "OrderStatusDescr", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.Suppliers", "Address", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Suppliers", "Surburb", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Suppliers", "City", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Suppliers", "Country", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Suppliers", "Province", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("dbo.Suppliers", "SupplierEmailAddress", c => c.String(nullable: false, maxLength: 35));
        }
        
        public override void Down()
        {
            AlterColumn("dbo.Suppliers", "SupplierEmailAddress", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Suppliers", "Province", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Suppliers", "Country", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Suppliers", "City", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Suppliers", "Surburb", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Suppliers", "Address", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.OrderStatus", "OrderStatusDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.VehicleTypes", "VehTypeImg", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.VehicleTypes", "VehTypeDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.VehicleMakes", "VehMakeDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Vehicles", "VehServiceIntervalUnit", c => c.String());
            AlterColumn("dbo.Vehicles", "VehServiceInterval", c => c.String(nullable: false));
            AlterColumn("dbo.Vehicles", "VehLicenseNum", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Vehicles", "VehRegNum", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Vehicles", "VehVinNum", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Vehicles", "VehEngineNum", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Vehicles", "VehModel", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Countries", "CountryDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Provinces", "ProvinceDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.RainfallRecords", "RecordMeasurement", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AlterColumn("dbo.Customers", "Province", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Customers", "Country", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Customers", "City", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Customers", "Surburb", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Customers", "Address", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Customers", "CompanyName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Customers", "ContactPersonalEmailAddress", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Silos", "SiloStatus", c => c.String());
            AlterColumn("dbo.Silos", "SiloDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.FieldStages", "FieldStageDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.CropTypes", "MaturityDays", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.CropTypes", "CropTypeDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.CropCycles", "CropCycleDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Plantations", "PlantationStatus", c => c.String(maxLength: 50));
            AlterColumn("dbo.Plantations", "ExpectedYieldUnit", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Plantations", "RefugeSeedUnit", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.InventoryTypes", "InvTypeDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Inventories", "InvSIUnit", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Inventories", "InvCode", c => c.String(nullable: false));
            AlterColumn("dbo.Inventories", "InvDescr", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.InventoryTreatments", "TreatmentUnit", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.FieldStatus", "StatPreConditions", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.FieldStatus", "FieldStatDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.NaturalDisasters", "NatDisasterPrecautions", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.NaturalDisasters", "NatDisasterDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.BiologicalDisasters", "BioDisasterNotes", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.BiologicalDisasters", "BioDisasterDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Fields", "FieldName", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.Lands", "LandName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Farms", "FarmName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Orders", "OrderItem", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Audits", "AuditRefAtrribute", c => c.String());
            AlterColumn("dbo.Audits", "TrxOldRecord", c => c.String());
            AlterColumn("dbo.Audits", "TrxNewRecord", c => c.String());
            AlterColumn("dbo.Audits", "AuditRefTable", c => c.String());
            AlterColumn("dbo.Titles", "TitleDescr", c => c.String(nullable: false, maxLength: 4));
            AlterColumn("dbo.Genders", "GenderDescr", c => c.String(nullable: false, maxLength: 10));
            AlterColumn("dbo.FarmWorkerTypes", "FarmWorkerTypeActiveStatus", c => c.String(nullable: false));
            AlterColumn("dbo.FarmWorkerTypes", "FarmWorkerTypeDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.FarmWorkers", "Province", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.FarmWorkers", "Country", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.FarmWorkers", "City", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.FarmWorkers", "Surburb", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.FarmWorkers", "Address", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.FarmWorkers", "FarmWorkerLName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.FarmWorkers", "FarmWorkerFName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Users", "UserLName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Users", "UserFName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Users", "UserPassword", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Users", "UserEmailAddress", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Users", "UserName", c => c.String(nullable: false, maxLength: 50));
            DropColumn("dbo.VehicleServices", "VehicleServiceRecordUnit");
            DropColumn("dbo.FarmWorkerTypes", "FarmWorkerTypeNotes");
            DropColumn("dbo.FarmWorkers", "FarmWorkerImg");
        }
    }
}
