//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(SiloHarvestMetaData))]
    public partial class SiloHarvest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SiloHarvest()
        {
            this.SiloHarvestSales = new HashSet<SiloHarvestSale>();
        }
    
        public int SiloHarvestID { get; set; }
        public Nullable<System.DateTime> SiloHarvestStoreStartDate { get; set; }
        public Nullable<System.DateTime> SiloHarvestStoreEndDate { get; set; }
        public double SiloHarvestTonnesStored { get; set; }
        public int SiloID { get; set; }
        public int PlantationID { get; set; }
    
        public virtual Plantation Plantation { get; set; }
        public virtual Silo Silo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiloHarvestSale> SiloHarvestSales { get; set; }
    }
}
