namespace WebApplication4.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class FirstName2 : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Logs", "UserAccessLevelID", "dbo.UserAccessLevels");
            DropIndex("dbo.Logs", new[] { "UserAccessLevelID" });
            AddColumn("dbo.FarmWorkers", "FarmWorkerImg", c => c.String());
            AddColumn("dbo.FarmWorkers", "Address", c => c.String(nullable: false, maxLength: 35));
            AddColumn("dbo.FarmWorkers", "Surburb", c => c.String(nullable: false, maxLength: 35));
            AddColumn("dbo.FarmWorkers", "City", c => c.String(nullable: false, maxLength: 35));
            AddColumn("dbo.FarmWorkers", "Country", c => c.String(nullable: false, maxLength: 35));
            AddColumn("dbo.FarmWorkers", "Province", c => c.String(nullable: false, maxLength: 36));
            AddColumn("dbo.FarmWorkerTypes", "FarmWorkerTypeNotes", c => c.String(maxLength: 50));
            AddColumn("dbo.Silos", "SiloStatus", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Sales", "PurchaseAgreement", c => c.String(nullable: false, maxLength: 255));
            AddColumn("dbo.Customers", "Address", c => c.String(nullable: false, maxLength: 35));
            AddColumn("dbo.Customers", "Surburb", c => c.String(nullable: false, maxLength: 35));
            AddColumn("dbo.Customers", "City", c => c.String(nullable: false, maxLength: 35));
            AddColumn("dbo.Customers", "Country", c => c.String(nullable: false, maxLength: 35));
            AddColumn("dbo.Customers", "Province", c => c.String(nullable: false, maxLength: 35));
            AddColumn("dbo.Vehicles", "VehName", c => c.String(nullable: false, maxLength: 30));
            AddColumn("dbo.Vehicles", "VehServiceIntervalUnit", c => c.String(nullable: false, maxLength: 5));
            AddColumn("dbo.VehicleServices", "VehicleServiceRecordUnit", c => c.String(nullable: false, maxLength: 5));
            AddColumn("dbo.VehicleTypes", "VehTypeImg", c => c.String(nullable: false, maxLength: 255));
            AddColumn("dbo.Suppliers", "Address", c => c.String(nullable: false, maxLength: 35));
            AddColumn("dbo.Suppliers", "Surburb", c => c.String(nullable: false, maxLength: 35));
            AddColumn("dbo.Suppliers", "City", c => c.String(nullable: false, maxLength: 35));
            AddColumn("dbo.Suppliers", "Country", c => c.String(nullable: false, maxLength: 35));
            AddColumn("dbo.Suppliers", "Province", c => c.String(nullable: false, maxLength: 36));
            AddColumn("dbo.Logs", "User", c => c.Int(nullable: false));
            AddColumn("dbo.Logs", "User1_UserID", c => c.Int());
            AlterColumn("dbo.Users", "UserName", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Users", "UserEmailAddress", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Users", "UserPassword", c => c.String(nullable: false, maxLength: 30));
            AlterColumn("dbo.Users", "UserFName", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Users", "UserLName", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.FarmWorkers", "FarmWorkerFName", c => c.String(nullable: false, maxLength: 15));
            AlterColumn("dbo.FarmWorkers", "FarmWorkerLName", c => c.String(nullable: false, maxLength: 15));
            AlterColumn("dbo.FarmWorkerTypes", "FarmWorkerTypeDescr", c => c.String(nullable: false, maxLength: 30));
            AlterColumn("dbo.FarmWorkerTypes", "FarmWorkerTypeActiveStatus", c => c.String(nullable: false, maxLength: 10));
            AlterColumn("dbo.Genders", "GenderDescr", c => c.String(nullable: false, maxLength: 8));
            AlterColumn("dbo.Titles", "TitleDescr", c => c.String(nullable: false, maxLength: 8));
            AlterColumn("dbo.Audits", "AuditRefTable", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Audits", "TrxNewRecord", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Audits", "TrxOldRecord", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Audits", "AuditRefAtrribute", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Orders", "OrderItem", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Farms", "FarmName", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Lands", "LandName", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Fields", "FieldName", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.BiologicalDisasters", "BioDisasterDescr", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.BiologicalDisasters", "BioDisasterNotes", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.NaturalDisasters", "NatDisasterDescr", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.NaturalDisasters", "NatDisasterPrecautions", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.FieldStatus", "FieldStatDescr", c => c.String(nullable: false, maxLength: 25));
            AlterColumn("dbo.FieldStatus", "StatPreConditions", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.InventoryTreatments", "TreatmentUnit", c => c.String(nullable: false, maxLength: 5));
            AlterColumn("dbo.Inventories", "InvDescr", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Inventories", "InvCode", c => c.String(nullable: false, maxLength: 10));
            AlterColumn("dbo.Inventories", "InvSIUnit", c => c.String(nullable: false, maxLength: 5));
            AlterColumn("dbo.InventoryTypes", "InvTypeDescr", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Plantations", "RefugeSeedUnit", c => c.String(nullable: false, maxLength: 5));
            AlterColumn("dbo.Plantations", "ExpectedYieldUnit", c => c.String(nullable: false, maxLength: 5));
            AlterColumn("dbo.Plantations", "PlantationStatus", c => c.String(maxLength: 20));
            AlterColumn("dbo.CropCycles", "CropCycleDescr", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.CropTypes", "CropTypeDescr", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.CropTypes", "MaturityDays", c => c.Int(nullable: false));
            AlterColumn("dbo.FieldStages", "FieldStageDescr", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.Silos", "SiloDescr", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.Customers", "ContactPersonalEmailAddress", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Customers", "CompanyName", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.RainfallRecords", "RecordMeasurement", c => c.Int(nullable: false));
            AlterColumn("dbo.Provinces", "ProvinceDescr", c => c.String(nullable: false, maxLength: 36));
            AlterColumn("dbo.Countries", "CountryDescr", c => c.String(nullable: false, maxLength: 25));
            AlterColumn("dbo.Vehicles", "VehModel", c => c.String(nullable: false, maxLength: 30));
            AlterColumn("dbo.Vehicles", "VehEngineNum", c => c.String(nullable: false, maxLength: 35));
            AlterColumn("dbo.Vehicles", "VehVinNum", c => c.String(nullable: false, maxLength: 17));
            AlterColumn("dbo.Vehicles", "VehRegNum", c => c.String(nullable: false, maxLength: 12));
            AlterColumn("dbo.Vehicles", "VehLicenseNum", c => c.String(nullable: false, maxLength: 15));
            AlterColumn("dbo.Vehicles", "VehServiceInterval", c => c.Int(nullable: false));
            AlterColumn("dbo.VehicleMakes", "VehMakeDescr", c => c.String(nullable: false, maxLength: 30));
            AlterColumn("dbo.VehicleTypes", "VehTypeDescr", c => c.String(nullable: false, maxLength: 30));
            AlterColumn("dbo.OrderStatus", "OrderStatusDescr", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.Suppliers", "SupplierEmailAddress", c => c.String(nullable: false, maxLength: 35));
            CreateIndex("dbo.Logs", "User1_UserID");
            AddForeignKey("dbo.Logs", "User1_UserID", "dbo.Users", "UserID");
            DropColumn("dbo.FarmWorkers", "FarmWorkerPhysicalAddress");
            DropColumn("dbo.Customers", "CompanyPhysAddress");
            DropColumn("dbo.Suppliers", "SupplierPhysAddress");
            DropColumn("dbo.Logs", "UserAccessLevelID");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Logs", "UserAccessLevelID", c => c.Int(nullable: false));
            AddColumn("dbo.Suppliers", "SupplierPhysAddress", c => c.String(nullable: false, maxLength: 10));
            AddColumn("dbo.Customers", "CompanyPhysAddress", c => c.String(nullable: false, maxLength: 100));
            AddColumn("dbo.FarmWorkers", "FarmWorkerPhysicalAddress", c => c.String(nullable: false, maxLength: 100));
            DropForeignKey("dbo.Logs", "User1_UserID", "dbo.Users");
            DropIndex("dbo.Logs", new[] { "User1_UserID" });
            AlterColumn("dbo.Suppliers", "SupplierEmailAddress", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.OrderStatus", "OrderStatusDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.VehicleTypes", "VehTypeDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.VehicleMakes", "VehMakeDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Vehicles", "VehServiceInterval", c => c.String(nullable: false));
            AlterColumn("dbo.Vehicles", "VehLicenseNum", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Vehicles", "VehRegNum", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Vehicles", "VehVinNum", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Vehicles", "VehEngineNum", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Vehicles", "VehModel", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Countries", "CountryDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Provinces", "ProvinceDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.RainfallRecords", "RecordMeasurement", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AlterColumn("dbo.Customers", "CompanyName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Customers", "ContactPersonalEmailAddress", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Silos", "SiloDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.FieldStages", "FieldStageDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.CropTypes", "MaturityDays", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.CropTypes", "CropTypeDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.CropCycles", "CropCycleDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Plantations", "PlantationStatus", c => c.String(maxLength: 50));
            AlterColumn("dbo.Plantations", "ExpectedYieldUnit", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Plantations", "RefugeSeedUnit", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.InventoryTypes", "InvTypeDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Inventories", "InvSIUnit", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Inventories", "InvCode", c => c.String(nullable: false));
            AlterColumn("dbo.Inventories", "InvDescr", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.InventoryTreatments", "TreatmentUnit", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.FieldStatus", "StatPreConditions", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.FieldStatus", "FieldStatDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.NaturalDisasters", "NatDisasterPrecautions", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.NaturalDisasters", "NatDisasterDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.BiologicalDisasters", "BioDisasterNotes", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.BiologicalDisasters", "BioDisasterDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Fields", "FieldName", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.Lands", "LandName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Farms", "FarmName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Orders", "OrderItem", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Audits", "AuditRefAtrribute", c => c.String(nullable: false));
            AlterColumn("dbo.Audits", "TrxOldRecord", c => c.String(nullable: false));
            AlterColumn("dbo.Audits", "TrxNewRecord", c => c.String(nullable: false));
            AlterColumn("dbo.Audits", "AuditRefTable", c => c.String());
            AlterColumn("dbo.Titles", "TitleDescr", c => c.String(nullable: false, maxLength: 4));
            AlterColumn("dbo.Genders", "GenderDescr", c => c.String(nullable: false, maxLength: 10));
            AlterColumn("dbo.FarmWorkerTypes", "FarmWorkerTypeActiveStatus", c => c.Boolean(nullable: false));
            AlterColumn("dbo.FarmWorkerTypes", "FarmWorkerTypeDescr", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.FarmWorkers", "FarmWorkerLName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.FarmWorkers", "FarmWorkerFName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Users", "UserLName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Users", "UserFName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Users", "UserPassword", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Users", "UserEmailAddress", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Users", "UserName", c => c.String(nullable: false, maxLength: 50));
            DropColumn("dbo.Logs", "User1_UserID");
            DropColumn("dbo.Logs", "User");
            DropColumn("dbo.Suppliers", "Province");
            DropColumn("dbo.Suppliers", "Country");
            DropColumn("dbo.Suppliers", "City");
            DropColumn("dbo.Suppliers", "Surburb");
            DropColumn("dbo.Suppliers", "Address");
            DropColumn("dbo.VehicleTypes", "VehTypeImg");
            DropColumn("dbo.VehicleServices", "VehicleServiceRecordUnit");
            DropColumn("dbo.Vehicles", "VehServiceIntervalUnit");
            DropColumn("dbo.Vehicles", "VehName");
            DropColumn("dbo.Customers", "Province");
            DropColumn("dbo.Customers", "Country");
            DropColumn("dbo.Customers", "City");
            DropColumn("dbo.Customers", "Surburb");
            DropColumn("dbo.Customers", "Address");
            DropColumn("dbo.Sales", "PurchaseAgreement");
            DropColumn("dbo.Silos", "SiloStatus");
            DropColumn("dbo.FarmWorkerTypes", "FarmWorkerTypeNotes");
            DropColumn("dbo.FarmWorkers", "Province");
            DropColumn("dbo.FarmWorkers", "Country");
            DropColumn("dbo.FarmWorkers", "City");
            DropColumn("dbo.FarmWorkers", "Surburb");
            DropColumn("dbo.FarmWorkers", "Address");
            DropColumn("dbo.FarmWorkers", "FarmWorkerImg");
            CreateIndex("dbo.Logs", "UserAccessLevelID");
            AddForeignKey("dbo.Logs", "UserAccessLevelID", "dbo.UserAccessLevels", "UserAccessLevelID", cascadeDelete: true);
        }
    }
}
